"""empty message

Revision ID: 01f968dde156
Revises: 65628660796e
Create Date: 2023-05-06 23:10:21.640245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f968dde156'
down_revision = '65628660796e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=50), nullable=False),
    sa.Column('terrain', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('parts')
    op.drop_table('frame')
    with op.batch_alter_table('favorites_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bike_part_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'bike_part', ['bike_part_id'], ['id'])
        batch_op.drop_column('parts_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parts_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'parts', ['parts_id'], ['id'])
        batch_op.drop_column('bike_part_id')

    op.create_table('frame',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('link', sa.VARCHAR(), nullable=False),
    sa.Column('brand', sa.VARCHAR(), nullable=False),
    sa.Column('frame_type', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('link', sa.VARCHAR(), nullable=False),
    sa.Column('size', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bike_part')
    # ### end Alembic commands ###
