"""empty message

Revision ID: 560eeafde244
Revises: 
Create Date: 2023-05-18 17:29:09.793263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560eeafde244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike_part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike_part', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
