"""empty message

Revision ID: 65628660796e
Revises: 1f2cc5f32498
Create Date: 2023-05-06 21:54:30.251813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65628660796e'
down_revision = '1f2cc5f32498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frame_type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.drop_column('frame_type')

    # ### end Alembic commands ###
