"""empty message

Revision ID: 76671a76a105
Revises: e314089f4927
Create Date: 2023-05-06 17:44:25.264192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76671a76a105'
down_revision = 'e314089f4927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
